### PR TITLE
Added LICENSE file

### PR DESCRIPTION
**Pull request by stefonarch**
Closes https://github.com/lxqt/lxqt-wayland-session/issues/13

### CODE REVIEW

**Comment by yan12125** [comment]
Looks good, thanks!

**Comment by stefonarch** [comment]
Found another one to include and it looks like GNU General Public License v3.0 is better to include all the others, although they are  not source code but configuration files mostly.

**Comment by stefonarch** [comment]
I got some inspiration also from here - that should be adressed too...
https://github.com/lxqt/lxqt-config/issues/966

**Comment by yan12125** [comment]
I'm not sure about "relicensed". I remember that happens only with permissions from the original author & contributors.

**Comment by stefonarch** [comment]
> I'm not sure about "relicensed". I remember that happens only with permissions from the original author & contributors.



> I'm not sure about "relicensed". I remember that happens only with permissions from the original author & contributors.

That would be we, the files based on lxqt-session. It looks like we can't include GPL3 otherwise, but as they are only config files I'm also not sure if this is necessary.

**Comment by yan12125** [comment]
I believe configuration files should be properly licensed as well.

**Comment by stefonarch** [comment]
> I believe configuration files should be properly licensed as well.

They are, no?

**Comment by yan12125** [comment]
> They are, no?

Yes, this is good. I was expressing my opinion about whether it is really necessary or not.

**Comment by stefonarch** [comment]
Does this need any change now? Licensing isn't my field really.

**Comment by yan12125** [comment]
Probably not, but my spare time in September is quite limited. I may not be able to double check this soon.

**Comment by stefonarch** [comment]
We could also use ef710a6c6a6e8e65a3dc52863567b00d3da58b6f + the single license files added, it's probably less complex and will be fine the same IMO.

**Comment by stefonarch** [comment]
Done. 
Not sure about the location of COPYING - put it both directories to which it applies?

**Comment by yan12125** [comment]
Thanks! Overall this looks good.

> Not sure about the location of COPYING - put it both directories to which it applies?

Probably better to put all LICENSE-related files in the same place (ex: the top-level folder). I remember some projects are doing that, and I often check only one place for licenses.

**Comment by stefonarch** [comment]
>Probably better to put all LICENSE-related files in the same place

Done.

**Comment by yan12125** [comment]
Thank you!

**Pull request merged**
