### PR TITLE
Add cosmic-comp (standalone)

### PR DESCRIPTION
**Pull request by antis81**
Minimal integration of the Cosmic compositor (`cosmic-comp` package).

**Notes:**
It helps to install `cosmic-launcher` (pendant to `lxqt-runner`) and `cosmic-settings-daemon` (creates default configuration files in `$XDG_CONFIG_HOME/cosmic`). Pressing `Super` key should open a text input to spawn applications (press twice after startup).

### CODE REVIEW

**Comment by stefonarch** [comment]
Did you try to run `lxqt-panel` on cosmic? Probably not.

**Comment by antis81** [comment]
Yes, I ran lxqt-panel and it starts fine… Why are you closing a completely valid PR in the first place?

**Comment by stefonarch** [comment]
I tested `lxqt-panel` on cosmic, it segfaulted. You would need to add a basic configuration here which starts `lxqt-session` at least but I doubt that we can support cosmic.

**Comment by stefonarch** [comment]
This snippet isn't different as inserting manually `cosmic-comp` in the Session settings. Besides some bugs those are the basic requirements IMO to add a compositor:
* lxqt-session is started and can be exited by `lxqt-leave --logout` and is basically identical on every compositor
* Panel's taskbar, right click settings menu, fancymenu, runner, desktop (right click too) and notifications should work.

**Comment by antis81** [comment]
Yeah I think I understand… On my setup I just (accidentally) launch `cosmic-comp` without an `lxqt-session`. So when you start `lxqt-panel` within that it should no longer segfault (Could you try that please?).

Actually the configuration can be done similar to that for `river`. Only instead of `riverctl` we use `cosmic-settings`. Restriction: Running LXQt and Cosmic in parallel will clash. This can be solved however pointing `$XDG_CONFIG_HOME/cosmic/v1` to `$XDG_CONFIG_HOME/lxqt/lxqt-cosmic/v1/…`). (don't know if that is already possible…)

**Comment by stefonarch** [comment]
I could launch the panel, but not even right click for configuring worked. 
I don't see any benefit of using cosmic-comp, but if you manage to create an usable session/configuration file why not.

**Comment by antis81** [comment]
Benefits…? Did you check cosmic-comp package dependencies? It's a pretty standalone compositor. The only dependency is `cosmic-settings-daemon` (other shortcuts don't work…??)

(Both packages `cosmic-launcher` and `cosmic-settings` (the GUI) are optional.)

Like other compositors cosmic-comp uses `xkb_config` to configure keyboard layouts. When configured the file is located in `~/.config/com.system76.CosmicComp/xkb_config` (defaults to `en_US`). 

Default shortcuts live in `/usr/share/cosmic/com.system76.CosmicSettings.Shortcuts/v1/defaults`.

(thought about sed'ing those maybe like done in other comp's…)

The crashes seem to be related to ZBus vs DBus. Shuold be solvable…

No other dependencies -> think that makes it worth a try…

**Comment by stefonarch** [comment]
>No other dependencies -> think that makes it worth a try…

It's your PR. I'll test it, the conditions to meet I've mentioned. Smithay is not wlroots.

**Comment by antis81** [comment]
Can we provide a session socket? The relevant snippet from `cosmic-session`:

```rust
Process::new()
    .with_executable("cosmic-comp")
    .with_env([("COSMIC_SESSION_SOCK", comp.as_raw_fd().to_string())])
    .with_on_exit(/* stops or restarts the process… */);
```

**Comment by antis81** [comment]
@stefonarch Not sure if and where the wayland library (`wlroots`) is actually queried (in LXQt session context)… However setting `smithay` instead of `wlroots` seems to have a positive effect. Please note that I am still on LXQt 2.0 (lots of X11 errors in output…). At least I can start a fully working lxqt-session at least from "inside" cosmic-comp (panel with menus etc.).

I don't think it is currently possible to make  lxqt-session the parent process. Because lxqt-session wants a display on start (hen egg issues :smile:)…

**Comment by stefonarch** [comment]
> I don't think it is currently possible to make lxqt-session the parent process. Because lxqt-session wants a display on start (hen egg issues 😄)…

`lxqt-session` is started by the chosen compositor, always.

**Comment by antis81** [comment]
>lxqt-session is started by the chosen compositor, always.

Yes… after startup lxqt-session becomes the parent process of the compositor. This is only logical because compositors commonly don't implement session management by themselves. Further it prevents killing the session by accident when the compositor e.g. crashes or needs a restart for other reasons (reconfigure).

Not sure why lxqt-session inherits `QApplication` though. This wants a `DISPLAY`; Can we even start the process "standalone"?

```
Failed to create wl_display (No such file or directory)
…
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
```

For cosmic-comp this means, there are two "blocker" issues to be able to integrate with LXQt:

1. Make cosmic-comp spawn as child process of lxqt-session (needs something like `cosmic-comp --exit-with-session lxqt-session`)
2. Provide a valid `COSMIC_SESSION_SOCK` file descriptor in this context
    NOTE: This should be DBus compatible; The variable itself is only handed over on cosmic-comp's initialization and not available in the actual session

Both rather no technical issues…

**Comment by stefonarch** [comment]
Adding simply `lxqt-session` to autostart in this compositor isn't working? And as I said, i doubt taskbar-plugin will work with it.

**Comment by antis81** [comment]
How would autostart solve this? The process tree has to look something like:

```
        ├─greetd───greetd───startx───xinit─┬─Xorg───5*[{Xorg}]
        │                                  └─lxqt-session
        │                                                 ├─kwin_x11───14*[{kwin_x11}]
```

**Comment by stefonarch** [comment]
No, please take a look at the other implementations. It's the compositor which starts `lxqt-session` everywhere.

**Comment by antis81** [comment]
Check your `pstree` or `htop` in the running session.

**Comment by stefonarch** [comment]
As cosmic-comp doesn't support `wlr-foreign-toplevel-management-unstable-v1` it can't be supported.

**Comment by antis81** [comment]
>As cosmic-comp doesn't support wlr-foreign-toplevel-management-unstable-v1 it can't be supported.

Not supported as in "not planned" or just status quo?

**Comment by stefonarch** [comment]
Any compositor which supports at least the wlr protocols used by the panel could be added. Niri is based on smithay but has support for it, so the taskbar is working fine with it.

**Pull request closed without merging**
