### PR TITLE
Added shortcut for fancymenu where possible

### PR DESCRIPTION
**Pull request by stefonarch**
On both compositors at first press the fancy menu is shown centered as window, after that it's ok.

### CODE REVIEW

**Review by tsujan — APPROVED** [review]
Good.

**Comment by stefonarch** [comment]
I was wondering if `qdbus` is usually installed and noticed it's part of qt-tools, and there is also `gdbus6`  installed here which works the same. It looks like it's needed by any other part of LXQt.

**Comment by tsujan** [comment]
`qdbus` is needed by many parts of LXQt. Every Qt user should install it under Linux.

**Comment by tsujan** [comment]
Oh, you mean its *binary*.

Anyway, nothing bad will happen if someone doesn't have it. All Arch users should have it, but probably not all Debian users.

**Pull request merged**
