### PR TITLE
startlxqtwayland.in: hide dependencies behind a variable COMPOSITOR

### PR DESCRIPTION
**Pull request by antohami**

### CODE REVIEW

**Comment by stefonarch** [comment]
GTM

**Comment by antohami** [comment]
Probably it was worth explaining why.
When building an RPM package, all these composers are detected as extra dependencies. But if you hide them behind a variable, this will not happen.

**Comment by tsujan** [comment]
@antohami, thanks for the explanation!

**Comment by stefonarch** [comment]
Thanks!

**Pull request merged**
